let a = [83,'Kala',,null,80,true]
console.log(a.length)
console.log(a[2])
a.push(false)
console.log(a.length)
console.log(a)
a.pop()
console.log(a.length)
console.log(a)
a.shift()
console.log(a.length)
console.log(a)
a.unshift(83)
console.log(a.length)
console.log(a)
let num = a.shift()
console.log(a.length)
console.log(a)
a.unshift(num)
console.log(a.length)
console.log(a)
for(let i=0;i<a.length;i++)
{
    console.log(typeof(a[i]))
}